; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.22"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[panopoly][download][type] = ""
projects[panopoly][download][url] = ""
projects[panopoly][type] = "module"
projects[panopoly][version] = "1.0-rc5"

projects[views_bulk_operations][version] = "3.1"

projects[admin_views][version] = "1.2"

projects[apps][version] = "1.0-beta7"
projects[apps][patches][0] = "http://drupal.org/files/1790902-check-last-modified-existing.patch"

projects[backports][version] = "1.0-alpha1"

projects[breakpoints][version] = "1.1"

projects[ctools][version] = "1.3"
projects[ctools][patches][0] = "http://drupal.org/files/ctools-1925018-61.patch"

projects[caption_filter][version] = "1.2"

projects[context_admin][version] = "1.2+0-dev"

projects[contextual-flyout-links][version] = "1.2"

projects[facetapi][version] = "1.3"

projects[date][version] = "2.6"

projects[date_popup_authored][version] = "1.1"

projects[defaultconfig][version] = "1.0-alpha9"

projects[defaultcontent][version] = "1.0-alpha9"
projects[defaultcontent][patches][0] = "http://drupal.org/files/1754428-allow-node-export-alter.patch"
projects[defaultcontent][patches][1] = "http://drupal.org/files/1757782-cannot-import-menu-hierarchy-8.patch"

projects[devel][version] = "1.3"

projects[draggableviews][version] = "2.0+56-dev"

projects[entity][version] = "1.1"

projects[entityconnect][version] = "1.0-rc1+5-dev"

projects[entityreference][version] = "1.0"

projects[fape][version] = "1.1+2-dev"

projects[features][version] = "2.0-rc1"

projects[field_group][version] = "1.1"

projects[fieldable_panels_panes][version] = "1.4+6-dev"

projects[file_entity][version] = "2.0-unstable7+94-dev"

projects[freepager][version] = "2.x-dev"

projects[getid3][version] = "1.0"

projects[html5_media][version] = "1.1"

projects[image_resize_filter][version] = "1.13"

projects[inline_entity_form][version] = "1.2+13-dev"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[linkit][version] = "2.6"

projects[media][version] = "2.0-unstable7+62-dev"

projects[media_vimeo][version] = "2.0-rc1"

projects[media_youtube][version] = "2.0-rc3"

projects[menu_block][version] = "2.3"

projects[module_filter][version] = "1.7"

projects[navbar][version] = "1.0-alpha10+8-dev"
projects[navbar][patches][0] = "http://drupal.org/files/navbar-conflict-1757466-14.patch"
projects[navbar][patches][1] = "http://drupal.org/files/z-index-heart-cools-2050559-1.patch"

projects[panelizer][version] = "3.1"

projects[panels][version] = "3.3+41-dev"

projects[panels_breadcrumbs][version] = "2.1"

projects[panopoly_admin][version] = "1.0-rc5"

projects[panopoly_core][version] = "1.0-rc5"

projects[panopoly_images][version] = "1.0-rc5"

projects[panopoly_magic][version] = "1.0-rc5"

projects[panopoly_pages][version] = "1.0-rc5"

projects[panopoly_search][version] = "1.0-rc5"

projects[panopoly_theme][version] = "1.0-rc5"

projects[panopoly_users][version] = "1.0-rc5"

projects[panopoly_widgets][version] = "1.0-rc5"

projects[panopoly_wysiwyg][version] = "1.0-rc5"

projects[pathauto][version] = "1.2"
projects[pathauto][patches][0] = "http://drupal.org/files/pathauto-persist-936222-130-pathauto-state.patch"

projects[pm_existing_pages][version] = "1.4"

projects[private_taxonomy][version] = "1.4+2-dev"

projects[save_draft][version] = "1.4"

projects[search_api][version] = "1.7"

projects[search_api_db][version] = "1.0-rc2"

projects[search_api_solr][version] = "1.1"

projects[simple_gmap][version] = "1.0"

projects[simplified_menu_admin][version] = "1.0-beta2"

projects[strongarm][version] = "2.0"

projects[tablefield][version] = "2.2"

projects[taxonomy_menu_block][version] = "1.0"

projects[token][version] = "1.5"

projects[uuid][version] = "1.0-alpha5"

projects[views][version] = "3.7"

projects[views_autocomplete_filters][version] = "1.0"

projects[weight][version] = "2.3+1-dev"

projects[wysiwyg][version] = "2.2"
projects[wysiwyg][patches][0] = "http://drupal.org/files/wysiwyg-table-format.patch"
projects[wysiwyg][patches][1] = "http://drupal.org/files/wysiwyg-arbitrary_image_paths_markitup-1786732-3.patch"
projects[wysiwyg][patches][2] = "http://drupal.org/files/wysiwyg-1802394-4.patch"

projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[omega][version] = "4.0-beta6"

projects[radix][version] = "2.0-beta5"

projects[responsive_bartik][version] = "1.0-beta2"

projects[zen][version] = "6.x-dev"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[barracuda][download][type] = ""
projects[barracuda][download][url] = ""
projects[barracuda][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[shark][download][type] = ""
projects[shark][download][url] = ""
projects[shark][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[markitup][download][type] = ""
libraries[markitup][download][url] = ""
libraries[markitup][directory_name] = "markitup"
libraries[markitup][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[respondjs][download][type] = ""
libraries[respondjs][download][url] = ""
libraries[respondjs][directory_name] = "respondjs"
libraries[respondjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[SolrPhpClient][download][type] = ""
libraries[SolrPhpClient][download][url] = ""
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[getid3][download][type] = ""
libraries[getid3][download][url] = ""
libraries[getid3][directory_name] = "getid3"
libraries[getid3][type] = "library"