; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0"

projects[addtoany][subdir] = "contrib"
projects[addtoany][version] = "4.6"

projects[admin_icons][subdir] = "contrib"
projects[admin_icons][version] = "4.6"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.1"

projects[advanced_link][subdir] = "contrib"
projects[advanced_link][version] = "1.3"

projects[apachesolr][subdir] = "contrib"
projects[apachesolr][version] = "1.7"

projects[apachesolr_autocomplete][subdir] = "contrib"
projects[apachesolr_autocomplete][version] = "1.4"

projects[apachesolr_field_collection][subdir] = "contrib"
projects[apachesolr_field_collection][version] = "1.0-alpha2+2-dev"

projects[apachesolr_panels][subdir] = "contrib"
projects[apachesolr_panels][version] = "1.1"

projects[apachesolr_stats][subdir] = "contrib"
projects[apachesolr_stats][version] = "1.0-beta1"

projects[apachesolr_user][subdir] = "contrib"
projects[apachesolr_user][version] = "1.x-dev"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.3"

projects[autocomplete_deluxe][subdir] = "contrib"
projects[autocomplete_deluxe][version] = "2.0-beta2+26-dev"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "3.x"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0-beta3"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "1.2"

projects[block_titlelink][subdir] = "contrib"
projects[block_titlelink][version] = "1.x"

projects[bookblock][subdir] = "contrib"
projects[bookblock][version] = "1.x-dev"

projects[boxes][subdir] = "contrib"
projects[boxes][version] = "1.2"

projects[breakpoints][subdir] = "contrib"
projects[breakpoints][version] = "1.1"

projects[calendar][subdir] = "contrib"
projects[calendar][version] = "3.5"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.2"

projects[caption_filter][subdir] = "contrib"
projects[caption_filter][version] = "1.2"

projects[cdn][subdir] = "contrib"
projects[cdn][version] = "2.x"

projects[cer][subdir] = "contrib"
projects[cer][version] = "2.x-dev"

projects[checklistapi][subdir] = "contrib"
projects[checklistapi][version] = "1.2"

projects[chosen][patch][2167697] = https://drupal.org/files/issues/chosen-drush_make-2167697-3.patch
projects[chosen][subdir] = "contrib"
projects[chosen][version] = "2.0-beta4"

projects[coder][subdir] = "contrib"
projects[coder][version] = "2.3"

projects[collapsiblock][subdir] = "contrib"
projects[collapsiblock][version] = "1.0"

projects[colorbox][patch][2088137] = https://drupal.org/files/issues/colorbox-drush_make_master-2088137-6.patch
projects[colorbox][subdir] = "contrib"
projects[colorbox][version] = "1.6"

projects[comment_block][subdir] = "contrib"
projects[comment_block][version] = "1.0"

projects[comment_goodness][subdir] = "contrib"
projects[comment_goodness][version] = "1.2"

projects[comment_notify][patch][2073573] = https://drupal.org/files/comment_notify-node_type-2073573-1.patch
projects[comment_notify][subdir] = "contrib"
projects[comment_notify][version] = "1.2"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.1"

projects[commerce_add_to_cart_confirmation][subdir] = "contrib"
projects[commerce_add_to_cart_confirmation][version] = "1.0-rc2"

projects[commerce_addressbook][subdir] = "contrib"
projects[commerce_addressbook][version] = "2.0-rc8"

projects[commerce_amex][subdir] = "contrib"
projects[commerce_amex][version] = "1.1"

projects[commerce_authnet][subdir] = "contrib"
projects[commerce_authnet][version] = "1.1"

projects[commerce_autosku][subdir] = "contrib"
projects[commerce_autosku][version] = "1.x"

projects[commerce_backoffice][subdir] = "contrib"
projects[commerce_backoffice][version] = "1.4"

projects[commerce_bean][subdir] = "contrib"
projects[commerce_bean][version] = "1.0-beta1"

projects[commerce_cba][subdir] = "contrib"
projects[commerce_cba][version] = "1.0-beta1"

projects[commerce_checkout_progress][subdir] = "contrib"
projects[commerce_checkout_progress][version] = "1.3"

projects[commerce_checkout_redirect][subdir] = "contrib"
projects[commerce_checkout_redirect][version] = "2.0-rc1"

projects[commerce_discount][subdir] = "contrib"
projects[commerce_discount][version] = "1.0-alpha"

projects[commerce_exactor][subdir] = "contrib"
projects[commerce_exactor][version] = "1.3"

projects[commerce_extra_price_formatters][subdir] = "contrib"
projects[commerce_extra_price_formatters][version] = "1.x"

projects[commerce_fancy_attributes][subdir] = "contrib"
projects[commerce_fancy_attributes][version] = "1.0"

projects[commerce_features][patch][1402762] = https://drupal.org/files/commerce_features-export-shipping-rate-1402762-8.patch
projects[commerce_features][subdir] = "contrib"
projects[commerce_features][version] = "1.x"

projects[commerce_firstdata_gge4][subdir] = "contrib"
projects[commerce_firstdata_gge4][version] = "1.0"

projects[commerce_flat_rate][subdir] = "contrib"
projects[commerce_flat_rate][version] = "1.0-beta2"

projects[commerce_hosted_pci][subdir] = "contrib"
projects[commerce_hosted_pci][version] = "1.0-rc2"

projects[commerce_kiala][subdir] = "contrib"
projects[commerce_kiala][version] = "1.0-rc1"

projects[commerce_message][subdir] = "contrib"
projects[commerce_message][version] = "1.0-rc3"

projects[commerce_migrate][subdir] = "contrib"
projects[commerce_migrate][version] = "1.1"

projects[commerce_moneybookers][subdir] = "contrib"
projects[commerce_moneybookers][version] = "1.x"

projects[commerce_nosto_tagging][subdir] = "contrib"
projects[commerce_nosto_tagging][version] = "1.0"

projects[commerce_payleap][subdir] = "contrib"
projects[commerce_payleap][version] = "1.1"

projects[commerce_paypal][subdir] = "contrib"
projects[commerce_paypal][version] = "2.3"

projects[commerce_physical][subdir] = "contrib"
projects[commerce_physical][version] = "1.x"

projects[commerce_search_api][subdir] = "contrib"
projects[commerce_search_api][version] = "1.3"

projects[commerce_shipping][subdir] = "contrib"
projects[commerce_shipping][version] = "2.1"

projects[compact_forms][subdir] = "contrib"
projects[compact_forms][version] = "1.0"

projects[conditional_fields][subdir] = "contrib"
projects[conditional_fields][version] = "3.0-alpha1"

projects[connector][subdir] = "contrib"
projects[connector][version] = "1.0-beta2"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.6"

projects[context_admin][subdir] = "contrib"
projects[context_admin][version] = "1.2+0-dev"

projects[context_entity_field][subdir] = "contrib"
projects[context_entity_field][version] = "1.1"

projects[context_uuid][subdir] = "contrib"
projects[context_uuid][version] = "1.x"

projects[contextual-flyout-links][subdir] = "contrib"
projects[contextual-flyout-links][version] = "1.2"

projects[crumbs][subdir] = "contrib"
projects[crumbs][version] = "2.2"

projects[ctools][patches][0] = "http://drupal.org/files/ctools-1925018-61.patch"
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.5"

projects[custom_formatters][subdir] = "contrib"
projects[custom_formatters][version] = "2.2"

projects[data_export_import][subdir] = "contrib"
projects[data_export_import][version] = "1.7"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[date_facets][subdir] = "contrib"
projects[date_facets][version] = "1.0-beta2"

projects[date_popup_authored][subdir] = "contrib"
projects[date_popup_authored][version] = "1.1"

projects[defaultconfig][subdir] = "contrib"
projects[defaultconfig][version] = "1.0-alpha9"

projects[defaultcontent][patches][0] = "http://drupal.org/files/1754428-allow-node-export-alter.patch"
projects[defaultcontent][patches][1] = "http://drupal.org/files/1757782-cannot-import-menu-hierarchy-8.patch"
projects[defaultcontent][subdir] = "contrib"
projects[defaultcontent][version] = "1.0-alpha9"

projects[design][subdir] = "design"
projects[design][version] = "1.x-dev"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5+4-dev"

projects[devel_themer][subdir] = "contrib"
projects[devel_themer][version] = "1.x"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[disqus][subdir] = "contrib"
projects[disqus][version] = "1.10"

projects[download_count][patch][2039451] = https://drupal.org/files/download_count-varchar_default_with_number-2039451-1.patch
projects[download_count][subdir] = "contrib"
projects[download_count][version] = "3.x"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][version] = "2.0+56-dev"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.7+5-dev"

projects[easy_breadcrumb][subdir] = "contrib"
projects[easy_breadcrumb][version] = "2.12"

projects[email][subdir] = "contrib"
projects[email][version] = "1.2"

projects[email_registration][subdir] = "contrib"
projects[email_registration][version] = "1.2"

projects[ember][subdir] = "contrib"
projects[ember][version] = "1.0-alpha4"

projects[entity2text][subdir] = "contrib"
projects[entity2text][version] = "1.x-dev"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entity_list_field][subdir] = "contrib"
projects[entity_list_field][version] = "1.0-alpha7+1-dev"

projects[entity_lister][subdir] = "contrib"
projects[entity_lister][version] = "1.0-beta1"

projects[entity_rules][subdir] = "contrib"
projects[entity_rules][version] = "1.0-alpha1"

projects[entity_view_mode][subdir] = "contrib"
projects[entity_view_mode][version] = "1.0-rc1"

projects[entitycache][subdir] = "contrib"
projects[entitycache][version] = "1.2"

projects[entityconnect][subdir] = "contrib"
projects[entityconnect][version] = "1.0-rc1+5-dev"

projects[entityform][subdir] = "contrib"
projects[entityform][version] = "2.0-alpha1+2-dev"


projects[entityform_block][type] = "module"
projects[entityform_block][version] = "1.x-dev"


projects[entityqueue][subdir] = "contrib"
projects[entityqueue][version] = "1.0-alpha3+5-dev"

projects[entityreference][patch][1580348] = https://drupal.org/files/1580348-universal-formatters-17.patch
projects[entityreference][patches][0] = "https://drupal.org/files/1580348-universal-formatters-17.patch"
projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1+3-dev"

projects[entityreference_count][subdir] = "contrib"
projects[entityreference_count][version] = "1.x-dev"

projects[entityreference_prepopulate][subdir] = "contrib"
projects[entityreference_prepopulate][version] = "1.5+5-dev"

projects[entityreference_view_widget][subdir] = "contrib"
projects[entityreference_view_widget][version] = "2.0-rc5+2-dev"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[examples][subdir] = "contrib"
projects[examples][version] = "1.x"

projects[facetapi][patch][1616518] = https://drupal.org/files/1616518-7-show-active-term.patch
projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.5"

projects[facetapi_bonus][subdir] = "contrib"
projects[facetapi_bonus][version] = "1.1"

projects[facetapi_select][subdir] = "contrib"
projects[facetapi_select][version] = "1.x-dev"

projects[facetapi_taxonomy_sort][subdir] = "contrib"
projects[facetapi_taxonomy_sort][version] = "1.0-beta1"

projects[fape][subdir] = "contrib"
projects[fape][version] = "1.1+2-dev"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-rc1"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[fences][subdir] = "contrib"
projects[fences][version] = "1.0"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"

projects[field_collection_tabs][subdir] = "contrib"
projects[field_collection_tabs][version] = "1.0"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[field_permissions][patch][1845798] = https://drupal.org/files/field_permissions.miscellaneous.1845798-3.patch
projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.x"

projects[field_placeholder][subdir] = "contrib"
projects[field_placeholder][version] = "1.0"

projects[field_slideshow][subdir] = "contrib"
projects[field_slideshow][version] = "1.82"

projects[fieldable_panels_panes][subdir] = "contrib"
projects[fieldable_panels_panes][version] = "1.4+6-dev"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-unstable7+94-dev"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.8"

projects[filter_protocols][subdir] = "contrib"
projects[filter_protocols][version] = "1.2"

projects[fivestar][subdir] = "contrib"
projects[fivestar][version] = "2.1"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.2"

projects[flexslider][subdir] = "contrib"
projects[flexslider][version] = "2.0-alpha1"

projects[follow][subdir] = "contrib"
projects[follow][version] = "2.0-alpha1"

projects[fontyourface][subdir] = "contrib"
projects[fontyourface][version] = "2.8+0-dev"

projects[form_builder][subdir] = "contrib"
projects[form_builder][version] = "1.4"

projects[forward][subdir] = "contrib"
projects[forward][version] = "1.4"

projects[fpa][subdir] = "contrib"
projects[fpa][version] = "2.3"

projects[freepager][subdir] = "contrib"
projects[freepager][version] = "2.x-dev"

projects[galleria][subdir] = "contrib"
projects[galleria][version] = "1.0-beta3"

projects[geocoder][subdir] = "contrib"
projects[geocoder][version] = "1.2"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "2.0-beta1"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[getid3][subdir] = "contrib"
projects[getid3][version] = "1.0"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.1"

projects[gravatar][subdir] = "contrib"
projects[gravatar][version] = "1.1"

projects[hand_me_down_field_formatter][subdir] = "contrib"
projects[hand_me_down_field_formatter][version] = "1.0-beta1"

projects[homebox][subdir] = "contrib"
projects[homebox][version] = "2.0-beta6+17-dev"

projects[html5_media][subdir] = "contrib"
projects[html5_media][version] = "1.1"

projects[http_client][subdir] = "contrib"
projects[http_client][version] = "2.4"

projects[httprl][subdir] = "contrib"
projects[httprl][version] = "1.14"

projects[icomoon][subdir] = "contrib"
projects[icomoon][version] = "1.0"

projects[icon][subdir] = "contrib"
projects[icon][version] = "1.0-beta5"

projects[image_resize_filter][subdir] = "contrib"
projects[image_resize_filter][version] = "1.13"

projects[imageblock][subdir] = "contrib"
projects[imageblock][version] = "1.3"

projects[imagecache_actions][subdir] = "contrib"
projects[imagecache_actions][version] = "1.3"

projects[imagecache_token][subdir] = "contrib"
projects[imagecache_token][version] = "1.x"

projects[inline_conditions][subdir] = "contrib"
projects[inline_conditions][version] = "1.0-alpha4"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5+6-dev"

projects[jcarousel][subdir] = "contrib"
projects[jcarousel][version] = "2.6"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4+5-dev"

projects[js_injector][subdir] = "contrib"
projects[js_injector][version] = "2.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2+5-dev"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[linkchecker][patch][2060243] = https://drupal.org/files/issues/linkchecker-scan_node-2060243-29.patch
projects[linkchecker][subdir] = "contrib"
projects[linkchecker][version] = "1.x"

projects[linkimagefield][subdir] = "contrib"
projects[linkimagefield][version] = "1.x-dev"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "2.6"

projects[login_destination][subdir] = "contrib"
projects[login_destination][version] = "1.1"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.4"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[markdown][subdir] = "contrib"
projects[markdown][version] = "1.1"

projects[masonry][subdir] = "contrib"
projects[masonry][version] = "2.0"

projects[masonry_views][subdir] = "contrib"
projects[masonry_views][version] = "1.0"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc5"

projects[media][patch][2093435] = https://drupal.org/files/2093435-media-js-dialog-issues.patch
projects[media][subdir] = "contrib"
projects[media][version] = "2.0-unstable7+62-dev"

projects[media_browser_plus][subdir] = "contrib"
projects[media_browser_plus][version] = "1.0-beta3"

projects[media_vimeo][subdir] = "contrib"
projects[media_vimeo][version] = "2.0-rc1"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "2.0-rc3"

projects[mediaelement][patch][2167729] = https://drupal.org/files/issues/mediaelement-drush_make_master-2167729-1.patch
projects[mediaelement][subdir] = "contrib"
projects[mediaelement][version] = "1.x"

projects[mediafront][subdir] = "contrib"
projects[mediafront][version] = "2.2+1-dev"

projects[memcache][subdir] = "contrib"
projects[memcache][version] = "1.x"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc3"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[menu_firstchild][subdir] = "contrib"
projects[menu_firstchild][version] = "1.1+1-dev"

projects[menu_item_visibility][subdir] = "contrib"
projects[menu_item_visibility][version] = "1.0-beta1"

projects[menu_token][subdir] = "contrib"
projects[menu_token][version] = "1.0-beta5"

projects[message][patch][2051751] = https://drupal.org/files/message-primary_nullable-2051751-7.patch
projects[message][subdir] = "contrib"
projects[message][version] = "1.x"

projects[message_notify][subdir] = "contrib"
projects[message_notify][version] = "2.5"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.4"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.6"

projects[migrate_d2d][subdir] = "contrib"
projects[migrate_d2d][version] = "2.x"

projects[migrate_extras][subdir] = "contrib"
projects[migrate_extras][version] = "2.5+4-dev"

projects[mimemail][subdir] = "contrib"
projects[mimemail][version] = "1.x"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2+4-dev"

projects[multiform][subdir] = "contrib"
projects[multiform][version] = "1.1"

projects[mvf][subdir] = "contrib"
projects[mvf][version] = "1.0-beta1+8-dev"

projects[navbar][patches][0] = "http://drupal.org/files/navbar-conflict-1757466-14.patch"
projects[navbar][patches][1] = "http://drupal.org/files/z-index-heart-cools-2050559-1.patch"
projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.5"

projects[nice_menus][subdir] = "contrib"
projects[nice_menus][version] = "2.5"

projects[node_display_fields][subdir] = "contrib"
projects[node_display_fields][version] = "1.3"

projects[nodeblock][subdir] = "contrib"
projects[nodeblock][version] = "1.3"

projects[nodeconnect][subdir] = "contrib"
projects[nodeconnect][version] = "1.0-alpha2"

projects[nodequeue][patch][2039453] = https://drupal.org/files/nodequeue-primary_without_default-2039453-3.patch
projects[nodequeue][subdir] = "contrib"
projects[nodequeue][version] = "3.x"

projects[nodereference_url][subdir] = "contrib"
projects[nodereference_url][version] = "1.12"

projects[oauth2_server][patch][2167733] = https://drupal.org/files/issues/oauth2_server-drush_make_master-2167733-6.patch
projects[oauth2_server][subdir] = "contrib"
projects[oauth2_server][version] = "1.x"

projects[oauth][patch][980340] = https://drupal.org/files/980340-d7.patch
projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.1+4-dev"

projects[oauthconnector][patch][2055325] = https://drupal.org/files/oauthconnector-state_csrf-2055325-1.patch
projects[oauthconnector][subdir] = "contrib"
projects[oauthconnector][version] = "1.x"

projects[options_element][subdir] = "contrib"
projects[options_element][version] = "1.9"

projects[page_title][subdir] = "contrib"
projects[page_title][version] = "2.7"

projects[panelizer][subdir] = "contrib"
projects[panelizer][version] = "3.1"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4+7-dev"

projects[panels_breadcrumbs][subdir] = "contrib"
projects[panels_breadcrumbs][version] = "2.1"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc1"

projects[panels_extra_layouts][subdir] = "contrib"
projects[panels_extra_layouts][version] = "2.0"

projects[panels_extra_styles][subdir] = "contrib"
projects[panels_extra_styles][version] = "1.1"

projects[pathauto][patch][2030983] = https://drupal.org/files/pathauto-2030983-respect-entity-path-language-2.patch
projects[pathauto][patches][0] = "http://drupal.org/files/pathauto-persist-936222-130-pathauto-state.patch"
projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[picture][subdir] = "contrib"
projects[picture][version] = "2.9"

projects[plupload][subdir] = "contrib"
projects[plupload][version] = "1.2"

projects[pm_existing_pages][subdir] = "contrib"
projects[pm_existing_pages][version] = "1.4"

projects[prettify][patch][2175555] = https://drupal.org/files/issues/prettify-drush_make-2175555-1.patch
projects[prettify][subdir] = "contrib"
projects[prettify][version] = "1.x"

projects[print][subdir] = "contrib"
projects[print][version] = "2.0-beta2"

projects[private_taxonomy][subdir] = "contrib"
projects[private_taxonomy][version] = "1.4+2-dev"

projects[profile2][subdir] = "contrib"
projects[profile2][version] = "1.3"

projects[proj4js][subdir] = "contrib"
projects[proj4js][version] = "1.2"

projects[querypath][subdir] = "contrib"
projects[querypath][version] = "2.x"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][version] = "3.4"

projects[realname][subdir] = "contrib"
projects[realname][version] = "1.1"

projects[recaptcha][subdir] = "contrib"
projects[recaptcha][version] = "1.11"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[remote_stream_wrapper][subdir] = "contrib"
projects[remote_stream_wrapper][version] = "1.0-beta4"

projects[responsive_preview][subdir] = "contrib"
projects[responsive_preview][version] = "1.1"

projects[rss_field_formatters][subdir] = "contrib"
projects[rss_field_formatters][version] = "1.2"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.8"

projects[save_draft][subdir] = "contrib"
projects[save_draft][version] = "1.4"

projects[scald][subdir] = "contrib"
projects[scald][version] = "1.3"

projects[scald_commerce_product][subdir] = "contrib"
projects[scald_commerce_product][version] = "1.0-alpha1"

projects[scald_flickr][subdir] = "contrib"
projects[scald_flickr][version] = "1.x-dev"

projects[scald_gallery][subdir] = "contrib"
projects[scald_gallery][version] = "2.0+1-dev"

projects[scald_instagram][subdir] = "contrib"
projects[scald_instagram][version] = "1.x-dev"

projects[scald_map][subdir] = "contrib"
projects[scald_map][version] = "1.x-dev"








projects[scald_soundcloud][subdir] = "contrib"
projects[scald_soundcloud][version] = "1.1"

projects[scald_twitter][subdir] = "contrib"
projects[scald_twitter][version] = "1.x-dev"

projects[scald_video][subdir] = "contrib"
projects[scald_video][version] = "2.0-alpha1"

projects[schema][subdir] = "contrib"
projects[schema][version] = "1.2"

projects[search404][subdir] = "contrib"
projects[search404][version] = "1.3"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.7"

projects[search_api_db][subdir] = "contrib"
projects[search_api_db][version] = "1.0-rc2"

projects[search_api_ranges][subdir] = "contrib"
projects[search_api_ranges][version] = "1.5"

projects[search_api_solr][subdir] = "contrib"
projects[search_api_solr][version] = "1.1"

projects[search_api_sorts][subdir] = "contrib"
projects[search_api_sorts][version] = "1.5"

projects[seckit][subdir] = "contrib"
projects[seckit][version] = "1.9"

projects[securelogin][subdir] = "contrib"
projects[securelogin][version] = "1.x"

projects[security_review][subdir] = "contrib"
projects[security_review][version] = "1.2"

projects[semantic_fields][subdir] = "contrib"
projects[semantic_fields][version] = "1.1-beta1"

projects[semantic_panels][subdir] = "contrib"
projects[semantic_panels][version] = "1.2+0-dev"

projects[semanticviews][subdir] = "contrib"
projects[semanticviews][version] = "1.0-rc2"

projects[seo_checker][subdir] = "contrib"
projects[seo_checker][version] = "1.8"

projects[seo_checklist][subdir] = "contrib"
projects[seo_checklist][version] = "4.1"

projects[serial][subdir] = "contrib"
projects[serial][version] = "1.2"

projects[services][subdir] = "contrib"
projects[services][version] = "3.4"

projects[session_expire][subdir] = "contrib"
projects[session_expire][version] = "1.0-alpha1+7-dev"

projects[sharethis][subdir] = "contrib"
projects[sharethis][version] = "2.x"

projects[simple_gmap][subdir] = "contrib"
projects[simple_gmap][version] = "1.0"

projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "2.1"

projects[simplenews][subdir] = "contrib"
projects[simplenews][version] = "1.1"

projects[simplified_menu_admin][subdir] = "contrib"
projects[simplified_menu_admin][version] = "1.0-beta2"

projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.2"

projects[site_verify][subdir] = "contrib"
projects[site_verify][version] = "1.x"

projects[smart_trim][subdir] = "contrib"
projects[smart_trim][version] = "1.4"

projects[socialmedia][subdir] = "contrib"
projects[socialmedia][version] = "1.0-beta13+3-dev"

projects[soundmanager2][subdir] = "contrib"
projects[soundmanager2][version] = "2.0-beta1"

projects[spaces][subdir] = "contrib"
projects[spaces][version] = "3.x"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[styleguide][subdir] = "contrib"
projects[styleguide][version] = "1.x"

projects[styles][subdir] = "contrib"
projects[styles][version] = "2.0-alpha8"

projects[superfish][subdir] = "contrib"
projects[superfish][version] = "1.9"

projects[system_stream_wrapper][subdir] = "contrib"
projects[system_stream_wrapper][version] = "1.0-rc1+2-dev"

projects[tablefield][subdir] = "contrib"
projects[tablefield][version] = "2.2"

projects[tagclouds][subdir] = "contrib"
projects[tagclouds][version] = "1.9"

projects[taxonomy_breadcrumb_lite][subdir] = "contrib"
projects[taxonomy_breadcrumb_lite][version] = "1.0"

projects[taxonomy_display][subdir] = "contrib"
projects[taxonomy_display][version] = "1.1"

projects[taxonomy_manager][subdir] = "contrib"
projects[taxonomy_manager][version] = "1.0"

projects[taxonomy_menu][subdir] = "contrib"
projects[taxonomy_menu][version] = "1.5"

projects[taxonomy_menu_block][version] = "1.0"
projects[taxonomy_menu_block][version] = "1.0"

projects[taxonomy_menu_trails][subdir] = "contrib"
projects[taxonomy_menu_trails][version] = "2.5"

projects[taxonomy_orphanage][subdir] = "contrib"
projects[taxonomy_orphanage][version] = "1.1"

projects[tb_megamenu][subdir] = "contrib"
projects[tb_megamenu][version] = "1.0-beta5"

projects[telephone][subdir] = "contrib"
projects[telephone][version] = "1.x-dev"

projects[term_reference_filter_by_views][subdir] = "contrib"
projects[term_reference_filter_by_views][version] = "2.0-beta2"

projects[term_reference_tree][subdir] = "contrib"
projects[term_reference_tree][version] = "1.10+0-dev"

projects[themekey][subdir] = "contrib"
projects[themekey][version] = "3.2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5+4-dev"

projects[token_filter][subdir] = "contrib"
projects[token_filter][version] = "1.1"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[twbs][subdir] = "contrib"
projects[twbs][version] = "3.x"

projects[twbs_bootstrap][subdir] = "contrib"
projects[twbs_bootstrap][version] = "3.x"

projects[twbs_contextual][subdir] = "contrib"
projects[twbs_contextual][version] = "3.x"

projects[twbs_fontawesome][subdir] = "contrib"
projects[twbs_fontawesome][version] = "3.0-unstable4+3-dev"

projects[twbs_holder][subdir] = "contrib"
projects[twbs_holder][version] = "3.x"

projects[twbs_jquery][subdir] = "contrib"
projects[twbs_jquery][version] = "3.x"

projects[twbs_less][subdir] = "contrib"
projects[twbs_less][version] = "3.x"

projects[twbs_navbar][subdir] = "contrib"
projects[twbs_navbar][version] = "3.x"

projects[units][subdir] = "contrib"
projects[units][version] = "1.0-beta1+2-dev"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha6+14-dev"

projects[uuid_entity_autocomplete][subdir] = "contrib"
projects[uuid_entity_autocomplete][version] = "1.0-beta1+0-dev"

projects[uuid_features][patch][2060587] = https://drupal.org/files/issues/uuid_features-entity_type-2060587-11.patch
projects[uuid_features][patches][0] = "https://drupal.org/files/issues/uuid_features-entity_type-2060587-11.patch"
projects[uuid_features][subdir] = "contrib"
projects[uuid_features][version] = "1.0-alpha4+54-dev"

projects[varnish][subdir] = "contrib"
projects[varnish][version] = "1.x"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_accordion][subdir] = "contrib"
projects[views_accordion][version] = "1.0-rc2"

projects[views_arguments_extras][subdir] = "contrib"
projects[views_arguments_extras][version] = "1.0-beta1"

projects[views_autocomplete_filters][subdir] = "contrib"
projects[views_autocomplete_filters][version] = "1.0"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta8+1-dev"

projects[views_php][subdir] = "contrib"
projects[views_php][version] = "1.0-alpha1+2-dev"

projects[views_responsive_grid][subdir] = "contrib"
projects[views_responsive_grid][version] = "1.3"

projects[views_rss][subdir] = "contrib"
projects[views_rss][version] = "2.0-rc3+7-dev"

projects[views_rss_itunes][subdir] = "contrib"
projects[views_rss_itunes][version] = "1.0-rc2"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.1"

projects[views_slideshow_jcarousel][subdir] = "contrib"
projects[views_slideshow_jcarousel][version] = "1.x-dev"

projects[views_slideshow_liquidcarousel][subdir] = "contrib"
projects[views_slideshow_liquidcarousel][version] = "1.0-beta2"

projects[views_ticker][subdir] = "contrib"
projects[views_ticker][version] = "2.0"

projects[vntf][subdir] = "contrib"
projects[vntf][version] = "1.0-beta6"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.12"

projects[webform-classes][subdir] = "contrib"
projects[webform-classes][version] = "2.0"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.2"

projects[webform_protected_downloads][subdir] = "contrib"
projects[webform_protected_downloads][version] = "1.0"

projects[weight][subdir] = "contrib"
projects[weight][version] = "2.3+1-dev"

projects[widgets][subdir] = "contrib"
projects[widgets][version] = "1.0-rc1"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.x"

projects[workbench_access][subdir] = "contrib"
projects[workbench_access][version] = "1.x"

projects[workbench_moderation][subdir] = "contrib"
projects[workbench_moderation][version] = "1.3+10-dev"

projects[wysiwyg][patches][0] = "http://drupal.org/files/wysiwyg-table-format.patch"
projects[wysiwyg][patches][1] = "http://drupal.org/files/wysiwyg-arbitrary_image_paths_markitup-1786732-3.patch"
projects[wysiwyg][patches][2] = "http://drupal.org/files/wysiwyg-1802394-4.patch"
projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[wysiwyg_filter][subdir] = "contrib"
projects[wysiwyg_filter][version] = "1.6-rc2"

projects[xautoload][subdir] = "contrib"
projects[xautoload][version] = "5.1"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.1"


; Themes
projects[omega][version] = "4.3"


; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

libraries[backbone][directory_name] = "backbone"
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = "http://backbonejs.org/backbone-min"
libraries[backbone][type] = "library"

libraries[chosen][directory_name] = "chosen"
libraries[chosen][download][type] = "git"
libraries[chosen][download][url] = "https://github.com/harvesthq/chosen"
libraries[chosen][type] = "library"

libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][download][type] = "git"
libraries[ckeditor][download][url] = "https://github.com/ckeditor/ckeditor-dev"
libraries[ckeditor][type] = "library"

libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox"
libraries[colorbox][type] = "library"

libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider"
libraries[flexslider][type] = "library"

libraries[font-awesome][directory_name] = "font-awesome"
libraries[font-awesome][download][type] = ""
libraries[font-awesome][download][url] = ""
libraries[font-awesome][type] = "library"

libraries[glip][directory_name] = "glip"
libraries[glip][download][type] = "git"
libraries[glip][download][url] = "https://github.com/halstead/glip"
libraries[glip][type] = "library"

libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][type] = "library"

libraries[jquery.timepicker][directory_name] = "jquery.timepicker"
libraries[jquery.timepicker][download][type] = ""
libraries[jquery.timepicker][download][url] = ""
libraries[jquery.timepicker][type] = "library"

libraries[jquery.ui][directory_name] = "jquery.ui"
libraries[jquery.ui][download][type] = ""
libraries[jquery.ui][download][url] = ""
libraries[jquery.ui][type] = "library"

libraries[json2][directory_name] = "json2"
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][type] = "library"

libraries[mediaelement][directory_name] = "mediaelement"
libraries[mediaelement][download][type] = ""
libraries[mediaelement][download][url] = ""
libraries[mediaelement][type] = "library"

libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][type] = "library"

libraries[nivo-slider][directory_name] = "nivo-slider"
libraries[nivo-slider][download][type] = ""
libraries[nivo-slider][download][url] = ""
libraries[nivo-slider][type] = "library"

libraries[profiler][directory_name] = "profiler"
libraries[profiler][download][type] = ""
libraries[profiler][download][url] = ""
libraries[profiler][type] = "library"

libraries[qtip][directory_name] = "qtip"
libraries[qtip][download][type] = ""
libraries[qtip][download][url] = ""
libraries[qtip][type] = "library"

libraries[soundmanager2][directory_name] = "soundmanager2"
libraries[soundmanager2][download][type] = ""
libraries[soundmanager2][download][url] = ""
libraries[soundmanager2][type] = "library"

libraries[superfish][directory_name] = "superfish"
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][type] = "library"

libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][type] = "library"

libraries[underscore][directory_name] = "underscore"
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][type] = "library"