; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[drustack][download][type] = ""
projects[drustack][download][url] = ""
projects[drustack][type] = "module"
projects[drustack][version] = "34.81+3-dev"
projects[drustack][patches][0] = "https://drupal.org/files/issues/backup_migrate-2277383-1.patch"
projects[drustack][patches][1] = "https://drupal.org/files/issues/chosen-drush_make-2167697-3.patch"
projects[drustack][patches][2] = "https://drupal.org/files/comment_notify-node_type-2073573-1.patch"
projects[drustack][patches][3] = "https://drupal.org/files/commerce_features-export-shipping-rate-1402762-8.patch"
projects[drustack][patches][4] = "https://drupal.org/files/field_permissions.miscellaneous.1845798-3.patch"
projects[drustack][patches][5] = "https://drupal.org/files/issues/l10n_client-browser_is_undefined_jquery_gt_19-2191771-3.patch"
projects[drustack][patches][6] = "https://drupal.org/files/issues/mediaelement-drush_make_master-2167729-1.patch"
projects[drustack][patches][7] = "https://drupal.org/files/message-primary_nullable-2051751-7.patch"
projects[drustack][patches][8] = "https://drupal.org/files/pathauto-2030983-respect-entity-path-language-2.patch"

projects[date][version] = "2.8"

projects[devel][version] = "1.5+4-dev"

projects[drustack_webform][version] = "34.x-dev"

projects[fontyourface][version] = "2.8"

projects[entityreference][version] = "1.1"
projects[entityreference][patches][0] = "https://drupal.org/files/1580348-universal-formatters-17.patch"

projects[inline_conditions][version] = "1.0-alpha4"

projects[inline_entity_form][version] = "1.5"

projects[libraries][version] = "2.2+5-dev"

projects[migrate_extras][version] = "2.5+4-dev"

projects[module_filter][version] = "2.0-alpha2+4-dev"

projects[navbar][version] = "1.5"

projects[rules][version] = "2.8"

projects[session_expire][version] = "1.0-alpha1+7-dev"

projects[system_stream_wrapper][version] = "1.0-rc1+2-dev"

projects[token][version] = "1.5+4-dev"

projects[transliteration][version] = "3.2"

projects[twbs_fontawesome][version] = "3.0-unstable4+3-dev"

projects[uuid][version] = "1.0-alpha6+14-dev"

projects[uuid_entity_autocomplete][version] = "1.0-beta1+0-dev"

projects[uuid_features][version] = "1.0-alpha4+54-dev"
projects[uuid_features][patches][0] = "https://drupal.org/files/issues/uuid_features-entity_type-2060587-11.patch"

projects[views][version] = "3.7+39-dev"

projects[views_data_export][version] = "3.0-beta8+1-dev"

projects[views_php][version] = "1.0-alpha1+2-dev"

projects[webform][version] = "4.2"

projects[workbench_moderation][version] = "1.3+10-dev"

; Themes
projects[ember][version] = "2.0-alpha2+34-dev"

projects[responsive_bartik][version] = "1.0"

projects[twbs_seven][version] = "3.0-unstable4+1-dev"

projects[twbs_stark][version] = "3.0-unstable4+0-dev"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[bootstrap][download][type] = ""
libraries[bootstrap][download][url] = ""
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = ""
libraries[chosen][download][url] = ""
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[font-awesome][download][type] = ""
libraries[font-awesome][download][url] = ""
libraries[font-awesome][directory_name] = "font-awesome"
libraries[font-awesome][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[holder][download][type] = ""
libraries[holder][download][url] = ""
libraries[holder][directory_name] = "holder"
libraries[holder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = ""
libraries[htmlpurifier][download][url] = ""
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery][download][type] = ""
libraries[jquery][download][url] = ""
libraries[jquery][directory_name] = "jquery"
libraries[jquery][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-bbq][download][type] = ""
libraries[jquery-bbq][download][url] = ""
libraries[jquery-bbq][directory_name] = "jquery-bbq"
libraries[jquery-bbq][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-cookie][download][type] = ""
libraries[jquery-cookie][download][url] = ""
libraries[jquery-cookie][directory_name] = "jquery-cookie"
libraries[jquery-cookie][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-form][download][type] = ""
libraries[jquery-form][download][url] = ""
libraries[jquery-form][directory_name] = "jquery-form"
libraries[jquery-form][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-once][download][type] = ""
libraries[jquery-once][download][url] = ""
libraries[jquery-once][directory_name] = "jquery-once"
libraries[jquery-once][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-ui][download][type] = ""
libraries[jquery-ui][download][url] = ""
libraries[jquery-ui][directory_name] = "jquery-ui"
libraries[jquery-ui][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[less.js][download][type] = ""
libraries[less.js][download][url] = ""
libraries[less.js][directory_name] = "less.js"
libraries[less.js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[less.php][download][type] = ""
libraries[less.php][download][url] = ""
libraries[less.php][directory_name] = "less.php"
libraries[less.php][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mediaelement][download][type] = ""
libraries[mediaelement][download][url] = ""
libraries[mediaelement][directory_name] = "mediaelement"
libraries[mediaelement][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[oauth2-server-php][download][type] = ""
libraries[oauth2-server-php][download][url] = ""
libraries[oauth2-server-php][directory_name] = "oauth2-server-php"
libraries[oauth2-server-php][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = ""
libraries[plupload][download][url] = ""
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[prettify][download][type] = ""
libraries[prettify][download][url] = ""
libraries[prettify][directory_name] = "prettify"
libraries[prettify][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[spyc][download][type] = ""
libraries[spyc][download][url] = ""
libraries[spyc][directory_name] = "spyc"
libraries[spyc][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"
