; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules
projects[apachesolr][subdir] = "contrib"
projects[apachesolr][version] = "1.7"

projects[apachesolr_autocomplete][subdir] = "contrib"
projects[apachesolr_autocomplete][version] = "1.4"

projects[apachesolr_field_collection][subdir] = "contrib"
projects[apachesolr_field_collection][version] = "1.0-alpha2+2-dev"

projects[apachesolr_panels][subdir] = "contrib"
projects[apachesolr_panels][version] = "1.1"

projects[apachesolr_stats][subdir] = "contrib"
projects[apachesolr_stats][version] = "1.0-beta1"

projects[apachesolr_user][subdir] = "contrib"
projects[apachesolr_user][version] = "1.x-dev"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.5"

projects[chosen][subdir] = "contrib"
projects[chosen][version] = "2.0-beta4"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.5"

projects[data_export_import][subdir] = "contrib"
projects[data_export_import][version] = "1.7"

projects[date_facets][subdir] = "contrib"
projects[date_facets][version] = "1.0-beta2"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.7"

projects[easy_breadcrumb][subdir] = "contrib"
projects[easy_breadcrumb][version] = "2.12"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1+3-dev"

projects[entityreference_prepopulate][subdir] = "contrib"
projects[entityreference_prepopulate][version] = "1.5+5-dev"

projects[entityreference_view_widget][subdir] = "contrib"
projects[entityreference_view_widget][version] = "2.0-rc5+2-dev"

projects[facetapi_bonus][subdir] = "contrib"
projects[facetapi_bonus][version] = "1.1"

projects[facetapi_select][subdir] = "contrib"
projects[facetapi_select][version] = "1.x-dev"

projects[facetapi_taxonomy_sort][subdir] = "contrib"
projects[facetapi_taxonomy_sort][version] = "1.0-beta1"

projects[fences][subdir] = "contrib"
projects[fences][version] = "1.0"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4+7-dev"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5+6-dev"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4+5-dev"

projects[js_injector][subdir] = "contrib"
projects[js_injector][version] = "2.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.4"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc3"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[menu_item_visibility][subdir] = "contrib"
projects[menu_item_visibility][version] = "1.0-beta1"

projects[menu_token][subdir] = "contrib"
projects[menu_token][version] = "1.0-beta5"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[mvf][subdir] = "contrib"
projects[mvf][version] = "1.0-beta1+8-dev"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.4"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc1"

projects[panels_extra_layouts][subdir] = "contrib"
projects[panels_extra_layouts][version] = "2.0"

projects[panels_extra_styles][subdir] = "contrib"
projects[panels_extra_styles][version] = "1.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[semantic_panels][subdir] = "contrib"
projects[semantic_panels][version] = "1.2+0-dev"

projects[semanticviews][subdir] = "contrib"
projects[semanticviews][version] = "1.0-rc2"

projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "2.1"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[taxonomy_manager][subdir] = "contrib"
projects[taxonomy_manager][version] = "1.0"

projects[taxonomy_menu][subdir] = "contrib"
projects[taxonomy_menu][version] = "1.5"

projects[taxonomy_menu_trails][subdir] = "contrib"
projects[taxonomy_menu_trails][version] = "2.5"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[units][subdir] = "contrib"
projects[units][version] = "1.0-beta1+2-dev"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

; Themes
projects[omega][version] = "4.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kitchen][download][type] = ""
projects[kitchen][download][url] = ""
projects[kitchen][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = ""
libraries[chosen][download][url] = ""
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[easing][download][type] = ""
libraries[easing][download][url] = ""
libraries[easing][directory_name] = "easing"
libraries[easing][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplehtmldom][download][type] = ""
libraries[simplehtmldom][download][url] = ""
libraries[simplehtmldom][directory_name] = "simplehtmldom"
libraries[simplehtmldom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

