; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.22"

; Profiles
projects[panopoly][type] = "profile"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[addressfield][version] = "1.0-beta4+5-dev"

projects[admin_views][version] = "1.2"

projects[advanced_help][version] = "1.0"

projects[advanced_link][version] = "1.3"

projects[scald][version] = "1.0"

projects[autocomplete_deluxe][version] = "2.0-beta2+26-dev"

projects[block_class][version] = "1.2"

projects[breakpoints][version] = "1.1"

projects[ctools][version] = "1.3"

projects[captcha][version] = "1.0"

projects[caption_filter][version] = "1.2"

projects[cer][version] = "2.x-dev"

projects[collapsiblock][version] = "1.0"

projects[colorbox][version] = "1.6"

projects[comment_block][version] = "1.0"

projects[comment_goodness][version] = "1.2"

projects[compact_forms][version] = "1.0"

projects[context][version] = "3.0-beta6"

projects[context_entity_field][version] = "1.1"

projects[contextual-flyout-links][version] = "1.2"

projects[facetapi][version] = "1.3"

projects[custom_formatters][version] = "2.2"

projects[date][version] = "2.6"

projects[defaultconfig][version] = "1.0-alpha9"

projects[defaultcontent][version] = "1.0-alpha9"

projects[design][subdir] = "design"
projects[design][version] = "1.x-dev"

projects[draggableviews][version] = "2.0"

projects[ds][version] = "2.4"

projects[email][version] = "1.2"

projects[entity][version] = "1.1"

projects[entity2text][version] = "1.x-dev"

projects[entity_list_field][version] = "1.0-alpha7+1-dev"

projects[entity_lister][version] = "1.0-beta1"

projects[entity_rules][version] = "1.0-alpha1"

projects[entity_view_mode][version] = "1.0-rc1"

projects[entityconnect][version] = "1.0-rc1+5-dev"

projects[entityform][version] = "2.0-alpha1+2-dev"

projects[entityreference][version] = "1.0+7-dev"

projects[entityreference_count][version] = "1.x-dev"

projects[eva][version] = "1.2"

projects[fape][version] = "1.1+2-dev"

projects[features][version] = "1.0"

projects[feeds][version] = "2.0-alpha8"

projects[fences][version] = "1.0"

projects[field_collection][version] = "1.0-beta5"

projects[field_collection_tabs][version] = "1.0"

projects[field_group][version] = "1.1"

projects[node_display_fields][version] = "1.3"

projects[field_placeholder][version] = "1.0"

projects[field_slideshow][version] = "1.82"

projects[fieldable_panels_panes][version] = "1.4+6-dev"

projects[file_entity][version] = "2.0-unstable7"

projects[filefield_sources][version] = "1.8"

projects[filter_protocols][version] = "1.2"

projects[flag][version] = "2.1"

projects[flexslider][version] = "2.0-alpha1"

projects[form_builder][version] = "1.4"

projects[fpa][version] = "2.3"

projects[freepager][version] = "2.x-dev"

projects[galleria][version] = "1.0-beta3"

projects[geocoder][version] = "1.2"

projects[geofield][version] = "2.0-beta1"

projects[geophp][version] = "1.7"

projects[getid3][version] = "1.0"

projects[hand_me_down_field_formatter][version] = "1.0-beta1"

projects[homebox][version] = "2.0-beta6+17-dev"

projects[imagecache_actions][version] = "1.3"

projects[image_resize_filter][version] = "1.13"

projects[imageblock][version] = "1.3"

projects[inline_entity_form][version] = "1.2+13-dev"

projects[jcarousel][version] = "2.6"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[linkimagefield][version] = "1.x-dev"

projects[linkit][version] = "2.6"

projects[logintoboggan][version] = "1.3"

projects[markdown][version] = "1.1"

projects[masonry][version] = "2.0"

projects[masonry_views][version] = "1.0"

projects[masquerade][version] = "1.0-rc5"

projects[media][version] = "2.0-unstable7"

projects[media_vimeo][version] = "2.0-rc1"

projects[media_youtube][version] = "2.0-rc3"

projects[mediafront][version] = "2.0"

projects[menu_attributes][version] = "1.0-rc2"

projects[menu_block][version] = "2.3"

projects[menu_firstchild][version] = "1.1+1-dev"

projects[menu_token][version] = "1.0-beta5"

projects[module_filter][version] = "1.7"

projects[multiform][version] = "1.0"

projects[navbar][version] = "1.0-alpha10+8-dev"
projects[navbar][patches][0] = "http://drupal.org/files/navbar-conflict-1757466-14.patch"
projects[navbar][patches][1] = "http://drupal.org/files/z-index-heart-cools-2050559-1.patch"

projects[references][version] = "2.1"

projects[nodeblock][version] = "1.3"

projects[nodeconnect][version] = "1.0-alpha2"

projects[nodereference_url][version] = "1.12"

projects[oauth][version] = "3.1+4-dev"

projects[openlayers][version] = "2.0-beta7+8-dev"

projects[options_element][version] = "1.9"

projects[page_title][version] = "2.7"

projects[panelizer][version] = "3.1"

projects[panels][version] = "3.3"

projects[panels_breadcrumbs][version] = "2.1"

projects[panopoly_admin][version] = "1.0-rc5"

projects[panopoly_core][version] = "1.0-rc5"

projects[panopoly_images][version] = "1.0-rc5"

projects[panopoly_magic][version] = "1.0-rc5"

projects[panopoly_pages][version] = "1.0-rc5"

projects[panopoly_search][version] = "1.0-rc5"

projects[panopoly_theme][version] = "1.0-rc5"

projects[panopoly_users][version] = "1.0-rc5"

projects[panopoly_widgets][version] = "1.0-rc5"

projects[panopoly_wysiwyg][version] = "1.0-rc5"

projects[pathauto][version] = "1.2"

projects[plupload][version] = "1.2"

projects[pm_existing_pages][version] = "1.4"

projects[print][version] = "2.0-beta2"

projects[profile2][version] = "1.3"

projects[proj4js][version] = "1.2"

projects[quicktabs][version] = "3.4"

projects[realname][version] = "1.1"

projects[redirect][version] = "1.0-rc1"

projects[remote_stream_wrapper][version] = "1.0-beta4"

projects[services][version] = "3.4"

projects[rss_field_formatters][version] = "1.2"

projects[rules][version] = "2.3"

projects[scald_gallery][version] = "2.0+1-dev"

projects[search_api][version] = "1.7"

projects[search_api_db][version] = "1.0-rc2"

projects[search_api_solr][version] = "1.1"

projects[semantic_fields][version] = "1.1-beta1"

projects[serial][version] = "1.2"

projects[simple_gmap][version] = "1.0"

projects[simplified_menu_admin][version] = "1.0-beta2"

projects[smart_trim][version] = "1.4"

projects[socialmedia][version] = "1.0-beta13+3-dev"

projects[soundmanager2][version] = "2.0-beta1"

projects[strongarm][version] = "2.0"

projects[superfish][version] = "1.9"

projects[tablefield][version] = "2.2"

projects[tagclouds][version] = "1.9"

projects[taxonomy_breadcrumb_lite][version] = "1.0"

projects[taxonomy_display][version] = "1.1"

projects[taxonomy_menu][version] = "1.4"

projects[taxonomy_menu_block][version] = "1.0"

projects[taxonomy_menu_trails][version] = "2.5"

projects[taxonomy_orphanage][version] = "1.1"

projects[telephone][version] = "1.x-dev"

projects[term_reference_filter_by_views][version] = "2.0-beta2"

projects[token][version] = "1.5"

projects[token_filter][version] = "1.1"

projects[views][version] = "3.7"

projects[views_accordion][version] = "1.0-rc2"

projects[views_arguments_extras][version] = "1.0-beta1"

projects[views_autocomplete_filters][version] = "1.0"

projects[vntf][version] = "1.0-beta6"

projects[views_responsive_grid][version] = "1.3"

projects[views_rss][version] = "2.0-rc3"

projects[views_rss_itunes][version] = "1.0-rc1+3-dev"

projects[views_slideshow][version] = "3.0"

projects[views_slideshow_jcarousel][version] = "1.x-dev"

projects[views_slideshow_liquidcarousel][version] = "1.0-beta2"

projects[views_ticker][version] = "2.0"

projects[webform][version] = "3.19"

projects[webform-classes][version] = "2.0"

projects[widgets][version] = "1.0-rc1"

projects[wysiwyg][version] = "2.2"

projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[ember][version] = "1.0-alpha4"

projects[omega][version] = "4.0-beta6"

projects[responsive_bartik][version] = "1.0-beta2"

; Modules
projects[admin_icons][type] = "module"
projects[admin_icons][download][type] = "git"
projects[admin_icons][download][url] = "http://git.drupal.org/project/admin_icons.git"
projects[admin_icons][download][branch] = "7.x-1.x"
projects[admin_icons][download][revision] = "60d9f28801533fecc92216a60d444d89d80e7611"

projects[context_omega][type] = "module"
projects[context_omega][download][type] = "git"
projects[context_omega][download][url] = "http://git.drupal.org/project/context_omega.git"
projects[context_omega][download][branch] = "7.x-1.x"
projects[context_omega][download][revision] = "fd28671ecabd804fe4adc4b281191ccbc25a8942"

projects[ds_id_arg][type] = "module"
projects[ds_id_arg][download][type] = "git"
projects[ds_id_arg][download][url] = "http://git.drupal.org/project/ds_id_arg.git"
projects[ds_id_arg][download][revision] = "ca0e3b407ba39b89128cbcabb3791af7ffb466ba"

projects[entityform_block][type] = "module"
projects[entityform_block][download][type] = "git"
projects[entityform_block][download][url] = "http://git.drupal.org/project/entityform_block.git"
projects[entityform_block][download][revision] = "e09efa564a382c66bb55cadaaab7c5e8f88f0b98"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[unlimitedfield_remove][download][type] = ""
projects[unlimitedfield_remove][download][url] = ""
projects[unlimitedfield_remove][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[shark][download][type] = ""
projects[shark][download][url] = ""
projects[shark][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[autopager][download][type] = ""
libraries[autopager][download][url] = ""
libraries[autopager][directory_name] = "autopager"
libraries[autopager][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[epiceditor][download][type] = ""
libraries[epiceditor][download][url] = ""
libraries[epiceditor][directory_name] = "epiceditor"
libraries[epiceditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = ""
libraries[flexslider][download][url] = ""
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[galleria][download][type] = ""
libraries[galleria][download][url] = ""
libraries[galleria][directory_name] = "galleria"
libraries[galleria][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[geoPHP][download][type] = ""
libraries[geoPHP][download][url] = ""
libraries[geoPHP][directory_name] = "geoPHP"
libraries[geoPHP][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[getid3][download][type] = ""
libraries[getid3][download][url] = ""
libraries[getid3][directory_name] = "getid3"
libraries[getid3][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[glip][download][type] = ""
libraries[glip][download][url] = ""
libraries[glip][directory_name] = "glip"
libraries[glip][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = ""
libraries[htmlpurifier][download][url] = ""
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jcarousel][download][type] = ""
libraries[jcarousel][download][url] = ""
libraries[jcarousel][directory_name] = "jcarousel"
libraries[jcarousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.jcarousel][download][type] = ""
libraries[jquery.jcarousel][download][url] = ""
libraries[jquery.jcarousel][directory_name] = "jquery.jcarousel"
libraries[jquery.jcarousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.timepicker][download][type] = ""
libraries[jquery.timepicker][download][url] = ""
libraries[jquery.timepicker][directory_name] = "jquery.timepicker"
libraries[jquery.timepicker][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.ui][download][type] = ""
libraries[jquery.ui][download][url] = ""
libraries[jquery.ui][directory_name] = "jquery.ui"
libraries[jquery.ui][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[liquidcarousel][download][type] = ""
libraries[liquidcarousel][download][url] = ""
libraries[liquidcarousel][directory_name] = "liquidcarousel"
libraries[liquidcarousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[markitup][download][type] = ""
libraries[markitup][download][url] = ""
libraries[markitup][directory_name] = "markitup"
libraries[markitup][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[masonry][download][type] = ""
libraries[masonry][download][url] = ""
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[nivo-slider][download][type] = ""
libraries[nivo-slider][download][url] = ""
libraries[nivo-slider][directory_name] = "nivo-slider"
libraries[nivo-slider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[openlayers][download][type] = ""
libraries[openlayers][download][url] = ""
libraries[openlayers][directory_name] = "openlayers"
libraries[openlayers][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = ""
libraries[plupload][download][url] = ""
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[profiler][download][type] = ""
libraries[profiler][download][url] = ""
libraries[profiler][directory_name] = "profiler"
libraries[profiler][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[respondjs][download][type] = ""
libraries[respondjs][download][url] = ""
libraries[respondjs][directory_name] = "respondjs"
libraries[respondjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplepie][download][type] = ""
libraries[simplepie][download][url] = ""
libraries[simplepie][directory_name] = "simplepie"
libraries[simplepie][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[SolrPhpClient][download][type] = ""
libraries[SolrPhpClient][download][url] = ""
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[soundmanager2][download][type] = ""
libraries[soundmanager2][download][url] = ""
libraries[soundmanager2][directory_name] = "soundmanager2"
libraries[soundmanager2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[vticker][download][type] = ""
libraries[vticker][download][url] = ""
libraries[vticker][directory_name] = "vticker"
libraries[vticker][type] = "library"


