; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[addtoany][subdir] = "contrib"
projects[addtoany][version] = "4.6"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.3"

projects[bookblock][subdir] = "contrib"
projects[bookblock][version] = "1.x-dev"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.5"

projects[calendar][subdir] = "contrib"
projects[calendar][version] = "3.5"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.2"

projects[chosen][subdir] = "contrib"
projects[chosen][version] = "2.0-beta4"

projects[comment_notify][subdir] = "contrib"
projects[comment_notify][version] = "1.2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.6"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5+4-dev"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.7+5-dev"

projects[easy_breadcrumb][subdir] = "contrib"
projects[easy_breadcrumb][version] = "2.12"

projects[fontyourface][subdir] = "contrib"
projects[fontyourface][version] = "2.8+0-dev"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityqueue][subdir] = "contrib"
projects[entityqueue][version] = "1.0-alpha3+5-dev"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"
projects[entityreference][patches][0] = "https://drupal.org/files/1580348-universal-formatters-17.patch"


projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[fences][subdir] = "contrib"
projects[fences][version] = "1.0"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-beta1+16-dev"

projects[styles][subdir] = "contrib"
projects[styles][version] = "2.0-alpha8"

projects[follow][subdir] = "contrib"
projects[follow][version] = "2.0-alpha1"

projects[forward][subdir] = "contrib"
projects[forward][version] = "1.4"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[icomoon][subdir] = "contrib"
projects[icomoon][version] = "1.0"

projects[icon][subdir] = "contrib"
projects[icon][version] = "1.0-beta5"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2+5-dev"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.4"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-alpha4+21-dev"

projects[media_browser_plus][subdir] = "contrib"
projects[media_browser_plus][version] = "1.0-beta3"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc3"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[menu_token][subdir] = "contrib"
projects[menu_token][version] = "1.0-beta5"

projects[migrate_extras][subdir] = "contrib"
projects[migrate_extras][version] = "2.5+4-dev"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2+4-dev"



projects[multiform][subdir] = "contrib"
projects[multiform][version] = "1.1"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.5"

projects[nice_menus][subdir] = "contrib"
projects[nice_menus][version] = "2.5"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.8"




projects[semantic_panels][subdir] = "contrib"
projects[semantic_panels][version] = "1.2"

projects[semanticviews][subdir] = "contrib"
projects[semanticviews][version] = "1.0-rc2"


projects[session_expire][subdir] = "contrib"
projects[session_expire][version] = "1.0-alpha1+7-dev"




projects[system_stream_wrapper][subdir] = "contrib"
projects[system_stream_wrapper][version] = "1.0-rc1+2-dev"




projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[superfish][subdir] = "contrib"
projects[superfish][version] = "1.9"

projects[taxonomy_menu][subdir] = "contrib"
projects[taxonomy_menu][version] = "1.5"

projects[taxonomy_menu_trails][subdir] = "contrib"
projects[taxonomy_menu_trails][version] = "2.5"

projects[tb_megamenu][subdir] = "contrib"
projects[tb_megamenu][version] = "1.0-beta5"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5+4-dev"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"


projects[twbs_fontawesome][subdir] = "contrib"
projects[twbs_fontawesome][version] = "3.0-unstable4+3-dev"


projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha6+14-dev"
projects[uuid_entity_autocomplete][subdir] = "contrib"
projects[uuid_entity_autocomplete][version] = "1.0-beta1+0-dev"
projects[uuid_features][subdir] = "contrib"
projects[uuid_features][version] = "1.0-alpha4+54-dev"
projects[uuid_features][patches][0] = "https://drupal.org/files/issues/uuid_features-entity_type-2060587-11.patch"



projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.1"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[wysiwyg][subdir] = "contrib"
projects[fontyourface][version] = "2.8"

projects[wysiwyg][subdir] = "contrib"
projects[inline_conditions][version] = "1.0-alpha4"

projects[wysiwyg][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5"












; Themes
projects[omega][version] = "4.3"



; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = ""
libraries[chosen][download][url] = ""
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = ""
libraries[flexslider][download][url] = ""
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[font-awesome][download][type] = ""
libraries[font-awesome][download][url] = ""
libraries[font-awesome][directory_name] = "font-awesome"
libraries[font-awesome][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[glip][download][type] = ""
libraries[glip][download][url] = ""
libraries[glip][directory_name] = "glip"
libraries[glip][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.timepicker][download][type] = ""
libraries[jquery.timepicker][download][url] = ""
libraries[jquery.timepicker][directory_name] = "jquery.timepicker"
libraries[jquery.timepicker][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.ui][download][type] = ""
libraries[jquery.ui][download][url] = ""
libraries[jquery.ui][directory_name] = "jquery.ui"
libraries[jquery.ui][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mediaelement][download][type] = ""
libraries[mediaelement][download][url] = ""
libraries[mediaelement][directory_name] = "mediaelement"
libraries[mediaelement][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[nivo-slider][download][type] = ""
libraries[nivo-slider][download][url] = ""
libraries[nivo-slider][directory_name] = "nivo-slider"
libraries[nivo-slider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[profiler][download][type] = ""
libraries[profiler][download][url] = ""
libraries[profiler][directory_name] = "profiler"
libraries[profiler][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[qtip][download][type] = ""
libraries[qtip][download][url] = ""
libraries[qtip][directory_name] = "qtip"
libraries[qtip][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[soundmanager2][download][type] = ""
libraries[soundmanager2][download][url] = ""
libraries[soundmanager2][directory_name] = "soundmanager2"
libraries[soundmanager2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"